@host = http://localhost:5217


POST {{host}}/api/Section/POST/
Content-Type:  application/json


{
  "id": 1,
  "name": "stasas",
  "sectionManagerId": 7
}

###Delete

DELETE {{host}}/api/Section/DELETE?sectionId=3