@host = http://localhost:5217


POST {{host}}/api/Section/POST/
Content-Type:  application/json


{
  "id": 2,
  "name": "IT",
  "sectionManagerId": 3
}

###Delete

DELETE {{host}}/api/Section/DELETE?sectionId=3