@host = http://localhost:5217


POST {{host}}/auth/register/
Content-Type:  application/json


{
    "firstName": "Jabel",
    "lastName": "Resendiz",
    "email": "jabelresendiz18@gmail.com",
    "password":"jabelResendiz1290"
}


###
