@host = http://localhost:5217


POST {{host}}/api/Authentication/register/
Content-Type:  application/json


{
  "name": "Jabel",
  "userName": "jabelResendiz030812",
  "email": "jabel#ka@gmail.com",
  "password": "jabelresendiZ03_04",
  "userRole": "Technician"
    
}





###
