@host = http://localhost:5217


POST {{host}}/api/Department/POST/
Content-Type:  application/json

{
  "id": 4,
  "name": "s90trin90asasg",
  "sectionId": 1,
  "sectionName":""
}


###

GET {{host}}/api/Department/GET_ALL

###

POST {{host}}/api/Department/GetPaged
Content-Type: application/json

{
  "PageNumber": 1,
  "PageSize": 20
}


###
GET {{host}}/api/Department/GetPaged?pageNumber=1&pageSize=2&sortColumn=Name&filters[sectionId]=21
