@host = http://localhost:5217


POST {{host}}/api/Department/POST/
Content-Type:  application/json

{
  "id": 4,
  "name": "s90trin90asasg",
  "sectionId": 1,
  "sectionName":""
}


###

GET {{host}}/api/Department/GET_ALL