@host = http://localhost:5217


POST {{host}}/api/Authentication/register/
Content-Type:  application/json

{
  "id": 90,
  "name": "Julio",
  "userName": "jJulioPerez",
  "email": "juliohernandez@gmail.com",
  "password": "julio9009_L",
  "userRole": "Technician",
  "specialty": "mechanic",
  "salary": 19090,
  "expYears": 10
}

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjEyIiwiZ2l2ZW5fbmFtZSI6Imp1bGlvMTEyOTAwOSIsImp0aSI6ImRhMDQzNWE0LWNjZDMtNGM2Mi1iZWMwLTFkOTk1ZGY2MGQxZCIsImV4cCI6MTczNjIzMDIzNywiaXNzIjoiRG93blRyYWNrIiwiYXVkIjoiRG93blRyYWNrIn0.dJWS_cpbogvi1hDSoH1FsdOanaK946a1oJqtPqsLWcA
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMiIsImdpdmVuX25hbWUiOiJqdWxpbzEyOTAwOSIsImp0aSI6ImIwMjhlZGQ2LWYyODMtNGUyMy04N2NiLTcyNGI1ZWRiYmE5NCIsImV4cCI6MTczNjIzMDIwNCwiaXNzIjoiRG93blRyYWNrIiwiYXVkIjoiRG93blRyYWNrIn0.EZSMrzzKSsIOrUURu7JYp0CSixXPItfDG3jwfouQfLw
###
