@host = http://localhost:5217


POST {{host}}/api/Authentication/register/
Content-Type:  application/json

{
  "id": 112,
  "name": "Julio",
  "userName": "julio909asas29",
  "email": "juliohernandez@gmail.com",
  "password": "julio9009_L",
  "userRole": "EquipmentReceptor",
  "specialty": "mechanic",
  "salary": 19090,
  "expYears": 10,
  "departamentId": 1,
  "sectionId": 1
}






###
