export * from "@/pages/dashboard_director/home"
export * from "@/pages/dashboard_director/decommissions_table"
export * from "@/pages/dashboard_director/maintenances_table"
export * from "@/pages/dashboard_director/equipment_transfers_table"
export * from "@/pages/dashboard_director/employees_table"
export * from "@/pages/dashboard_director/evaluations_table"
export * from "@/pages/dashboard_director/transfer_requests"