// <auto-generated />
using System;
using DownTrack.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DownTrack.Infrastructure.Migrations
{
    [DbContext(typeof(DownTrackContext))]
    partial class DownTrackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DownTrack.Domain.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfadquisition")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("DownTrack.Domain.Entities.EquipmentDecommissioning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfDecommissioning")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DecommissioningReason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId")
                        .IsUnique();

                    b.HasIndex("TechnicianId");

                    b.ToTable("EquipmentDecommissionings");
                });

            modelBuilder.Entity("DownTrack.Domain.Entities.Technician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ExpYears")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Salary")
                        .HasColumnType("double");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("DownTrack.Domain.Entities.EquipmentDecommissioning", b =>
                {
                    b.HasOne("DownTrack.Domain.Entities.Equipment", "Equipment")
                        .WithOne("EquipmentDecommissioning")
                        .HasForeignKey("DownTrack.Domain.Entities.EquipmentDecommissioning", "EquipmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DownTrack.Domain.Entities.Technician", "Technician")
                        .WithMany("EquipmentDecommissionings")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipment");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("DownTrack.Domain.Entities.Equipment", b =>
                {
                    b.Navigation("EquipmentDecommissioning")
                        .IsRequired();
                });

            modelBuilder.Entity("DownTrack.Domain.Entities.Technician", b =>
                {
                    b.Navigation("EquipmentDecommissionings");
                });
#pragma warning restore 612, 618
        }
    }
}
