
@host = http://localhost:5217


GET {{host}}/api/Technician/GET_ALL/
Authorization: Bearer ayJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYzdmMDFlNC1iNTY5LTQ0ZDYtYWQwNS1hNDMwMDY4YWQ3MzgiLCJnaXZlbl9uYW1lIjoiSmFiZWw5MCIsImZhbWlseV9uYW1lIjoiUmVzZW5kaXoiLCJqdGkiOiIzM2Q3MWZjNy05MmM3LTQ0YmQtYWU4YS00NmU1NTIzZGE5ZTciLCJleHAiOjE3MzYxMDE5NjAsImlzcyI6IkJ1YmJlckRpbm5lciIsImF1ZCI6IkJ1YmJlckRpbm5lciJ9.5OPSpYboP0T_vcR6iYhLhcbTVIZTIgFNJWtrsymsFvk
