
@host = http://localhost:5217


GET {{host}}/api/Technician/GetPaged/?pageNumber=1&pageSize=10
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiZ2l2ZW5fbmFtZSI6Imp1ZGVyaSIsImp0aSI6ImE3YTczNGExLTc3YWUtNDZmOS1iOGI2LWI1NjVkNWY5MzFmOSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlRlY2huaWNpYW4iLCJleHAiOjE3MzYyMzU5NzgsImlzcyI6IkRvd25UcmFjayIsImF1ZCI6IkRvd25UcmFjayJ9.W7bJ-4b7VsmRYQmRKOccFRU7MrQwOQeeSk4nEjoAmkE


###

GET {{host}}/api/EquipmentReceptor/GetPaged/?pageNumber=1&pageSize=10